fixed targetting, zlib error
SUBCOMMAND: # @@upb//:lex [action 'Compiling upb/lex/strtod.c', configuration: 20b301b7b42fe86ee96b1073759715860d04647bd5af7514a0f8ff2cf3b96f2f, execution platform: @@platforms//host:host, mnemonic: CppCompile]
(cd /private/var/tmp/_bazel_abinshahab/776cd7d396f0cd8906d56f52cbbbea44/execroot/_main && \
  exec env - \
    APPLE_SDK_PLATFORM=iPhoneOS \
    APPLE_SDK_VERSION_OVERRIDE=18.4 \
    PATH=/Users/abinshahab/Library/Caches/bazelisk/downloads/sha256/45cca81a839d7495258b19ee8371c7b891f350586ef37b9940f7b531eb654cc8/bin:/Users/abinshahab/.pyenv/versions/3.9.11/bin:/opt/homebrew/Cellar/pyenv/2.5.3/libexec:/opt/homebrew/Cellar/pyenv/2.5.3/plugins/python-build/bin:/Users/abinshahab/.atuin/bin:/opt/homebrew/opt/sqlite/bin:/Users/abinshahab/go/1.22.4/bin:/Users/abinshahab/.goenv/versions/1.22.4/bin:/Users/abinshahab/.goenv/bin:/Users/abinshahab/.nvm/versions/node/v16.18.0/bin:/Users/abinshahab/.krew/bin:/Users/abinshahab/.pyenv/shims:/Users/abinshahab/.local/bin:/usr/local/go/bin:/opt/homebrew/bin:/usr/local/bin:/System/Cryptexes/App/usr/bin:/usr/bin:/bin:/usr/sbin:/sbin:/opt/homebrew/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/local/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/appleinternal/bin:/opt/appleinternal/bin:/opt/apple/bin:/Library/Apple/usr/bin:/opt/xbs/bin:/usr/appleinternal/bin:/private/var/tanuki:/Applications/Wireshark.app/Contents/MacOS:/usr/local/go/bin:/opt/homebrew/bin:/Users/abinshahab/.goenv/shims \
    XCODE_VERSION_OVERRIDE=16.3.0.16E6140e \
    ZERO_AR_DATE=1 \
  external/local_config_apple_cc/wrapped_clang '-D_FORTIFY_SOURCE=1' -fstack-protector -fcolor-diagnostics -Wall -Wthread-safety -Wself-assign -fno-omit-frame-pointer -g0 -O2 -DNDEBUG '-DNS_BLOCK_ASSERTIONS=1' '-fdebug-prefix-map=__BAZEL_EXECUTION_ROOT__=.' '-fdebug-prefix-map=__BAZEL_XCODE_DEVELOPER_DIR__=/PLACEHOLDER_DEVELOPER_DIR' -iquote external/upb -iquote bazel-out/darwin_arm64-opt/bin/external/upb -MD -MF bazel-out/darwin_arm64-opt/bin/external/upb/_objs/lex/strtod.d '-frandom-seed=bazel-out/darwin_arm64-opt/bin/external/upb/_objs/lex/strtod.o' -isysroot __BAZEL_XCODE_SDKROOT__ -F__BAZEL_XCODE_SDKROOT__/System/Library/Frameworks -F__BAZEL_XCODE_DEVELOPER_DIR__/Platforms/iPhoneOS.platform/Developer/Library/Frameworks -no-canonical-prefixes -pthread '-std=c99' -Wall -Wstrict-prototypes -no-canonical-prefixes -Wno-builtin-macro-redefined '-D__DATE__="redacted"' '-D__TIMESTAMP__="redacted"' '-D__TIME__="redacted"' -target arm64e-apple-ios18.4 -c external/upb/upb/lex/strtod.c -o bazel-out/darwin_arm64-opt/bin/external/upb/_objs/lex/strtod.o)
ERROR: /private/var/tmp/_bazel_abinshahab/776cd7d396f0cd8906d56f52cbbbea44/external/zlib/BUILD.bazel:37:11: Compiling zutil.c [for tool] failed: (Exit 1): sandbox-exec failed: error executing CppCompile command
  (cd /private/var/tmp/_bazel_abinshahab/776cd7d396f0cd8906d56f52cbbbea44/sandbox/darwin-sandbox/257/execroot/_main && \
  exec env - \
    APPLE_SDK_PLATFORM=iPhoneOS \
    APPLE_SDK_VERSION_OVERRIDE=18.4 \
    DEVELOPER_DIR=/Applications/Xcode2.app/Contents/Developer \
    PATH=/Users/abinshahab/Library/Caches/bazelisk/downloads/sha256/45cca81a839d7495258b19ee8371c7b891f350586ef37b9940f7b531eb654cc8/bin:/Users/abinshahab/.pyenv/versions/3.9.11/bin:/opt/homebrew/Cellar/pyenv/2.5.3/libexec:/opt/homebrew/Cellar/pyenv/2.5.3/plugins/python-build/bin:/Users/abinshahab/.atuin/bin:/opt/homebrew/opt/sqlite/bin:/Users/abinshahab/go/1.22.4/bin:/Users/abinshahab/.goenv/versions/1.22.4/bin:/Users/abinshahab/.goenv/bin:/Users/abinshahab/.nvm/versions/node/v16.18.0/bin:/Users/abinshahab/.krew/bin:/Users/abinshahab/.pyenv/shims:/Users/abinshahab/.local/bin:/usr/local/go/bin:/opt/homebrew/bin:/usr/local/bin:/System/Cryptexes/App/usr/bin:/usr/bin:/bin:/usr/sbin:/sbin:/opt/homebrew/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/local/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/appleinternal/bin:/opt/appleinternal/bin:/opt/apple/bin:/Library/Apple/usr/bin:/opt/xbs/bin:/usr/appleinternal/bin:/private/var/tanuki:/Applications/Wireshark.app/Contents/MacOS:/usr/local/go/bin:/opt/homebrew/bin:/Users/abinshahab/.goenv/shims \
    SDKROOT=/Applications/Xcode2.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS18.4.sdk \
    TMPDIR=/var/folders/yj/t4s8y78932l8st32y242jcfm0000gn/T/ \
    XCODE_VERSION_OVERRIDE=16.3.0.16E6140e \
    ZERO_AR_DATE=1 \
  /usr/bin/sandbox-exec -f /private/var/tmp/_bazel_abinshahab/776cd7d396f0cd8906d56f52cbbbea44/sandbox/darwin-sandbox/257/sandbox.sb /var/tmp/_bazel_abinshahab/install/96e26d97222159f904e14600d7490eb0/process-wrapper '--timeout=0' '--kill_delay=15' '--stats=/private/var/tmp/_bazel_abinshahab/776cd7d396f0cd8906d56f52cbbbea44/sandbox/darwin-sandbox/257/stats.out' external/local_config_apple_cc/wrapped_clang '-D_FORTIFY_SOURCE=1' -fstack-protector -fcolor-diagnostics -Wall -Wthread-safety -Wself-assign -fno-omit-frame-pointer -g0 -O2 -DNDEBUG '-DNS_BLOCK_ASSERTIONS=1' '-fdebug-prefix-map=__BAZEL_EXECUTION_ROOT__=.' '-fdebug-prefix-map=__BAZEL_XCODE_DEVELOPER_DIR__=/PLACEHOLDER_DEVELOPER_DIR' -iquote external/zlib -iquote bazel-out/darwin_arm64-opt-exec-ST-4b10531d2bd0/bin/external/zlib -isystem external/zlib/zlib/include -isystem bazel-out/darwin_arm64-opt-exec-ST-4b10531d2bd0/bin/external/zlib/zlib/include -MD -MF bazel-out/darwin_arm64-opt-exec-ST-4b10531d2bd0/bin/external/zlib/_objs/zlib/zutil.d '-frandom-seed=bazel-out/darwin_arm64-opt-exec-ST-4b10531d2bd0/bin/external/zlib/_objs/zlib/zutil.o' -isysroot __BAZEL_XCODE_SDKROOT__ -F__BAZEL_XCODE_SDKROOT__/System/Library/Frameworks -F__BAZEL_XCODE_DEVELOPER_DIR__/Platforms/MacOSX.platform/Developer/Library/Frameworks -no-canonical-prefixes -pthread -g0 -Wno-deprecated-non-prototype -Wno-unused-variable -Wno-implicit-function-declaration -no-canonical-prefixes -Wno-builtin-macro-redefined '-D__DATE__="redacted"' '-D__TIMESTAMP__="redacted"' '-D__TIME__="redacted"' -target arm64e-apple-ios18.4 -c external/zlib/zutil.c -o bazel-out/darwin_arm64-opt-exec-ST-4b10531d2bd0/bin/external/zlib/_objs/zlib/zutil.o)
In file included from external/zlib/zutil.c:8:
external/zlib/zutil.h:170:11: warning: 'OS_CODE' macro redefined [-Wmacro-redefined]
  170 | #  define OS_CODE 19
      |           ^
external/zlib/zutil.h:141:11: note: previous definition is here
  141 | #  define OS_CODE  7
      |           ^
In file included from external/zlib/zutil.c:10:
In file included from external/zlib/gzguts.h:21:
In file included from /Applications/Xcode2.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS18.4.sdk/usr/include/stdio.h:61:
/Applications/Xcode2.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS18.4.sdk/usr/include/_stdio.h:318:7: error: expected identifier or '('
  318 | FILE    *fdopen(int, const char *) __DARWIN_ALIAS_STARTING(__MAC_10_6, __IPHONE_2_0, __DARWIN_ALIAS(fdopen));
      |          ^
external/zlib/zutil.h:147:33: note: expanded from macro 'fdopen'
  147 | #        define fdopen(fd,mode) NULL /* No fdopen() */
      |                                 ^
/Applications/Xcode2.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/17/include/__stddef_null.h:26:16: note: expanded from macro 'NULL'
   26 | #define NULL ((void*)0)
      |                ^
In file included from external/zlib/zutil.c:10:
In file included from external/zlib/gzguts.h:21:
In file included from /Applications/Xcode2.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS18.4.sdk/usr/include/stdio.h:61:
/Applications/Xcode2.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS18.4.sdk/usr/include/_stdio.h:318:7: error: expected ')'
external/zlib/zutil.h:147:33: note: expanded from macro 'fdopen'
  147 | #        define fdopen(fd,mode) NULL /* No fdopen() */
      |                                 ^
/Applications/Xcode2.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/17/include/__stddef_null.h:26:16: note: expanded from macro 'NULL'
   26 | #define NULL ((void*)0)
      |                ^
/Applications/Xcode2.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS18.4.sdk/usr/include/_stdio.h:318:7: note: to match this '('
external/zlib/zutil.h:147:33: note: expanded from macro 'fdopen'
  147 | #        define fdopen(fd,mode) NULL /* No fdopen() */
      |                                 ^
/Applications/Xcode2.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/17/include/__stddef_null.h:26:15: note: expanded from macro 'NULL'
   26 | #define NULL ((void*)0)
      |               ^
In file included from external/zlib/zutil.c:10:
In file included from external/zlib/gzguts.h:21:
In file included from /Applications/Xcode2.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS18.4.sdk/usr/include/stdio.h:61:
/Applications/Xcode2.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS18.4.sdk/usr/include/_stdio.h:318:7: error: expected ')'
  318 | FILE    *fdopen(int, const char *) __DARWIN_ALIAS_STARTING(__MAC_10_6, __IPHONE_2_0, __DARWIN_ALIAS(fdopen));
      |          ^
external/zlib/zutil.h:147:33: note: expanded from macro 'fdopen'
  147 | #        define fdopen(fd,mode) NULL /* No fdopen() */
      |                                 ^
/Applications/Xcode2.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/17/include/__stddef_null.h:26:22: note: expanded from macro 'NULL'
   26 | #define NULL ((void*)0)
      |                      ^
/Applications/Xcode2.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS18.4.sdk/usr/include/_stdio.h:318:7: note: to match this '('
external/zlib/zutil.h:147:33: note: expanded from macro 'fdopen'
  147 | #        define fdopen(fd,mode) NULL /* No fdopen() */
      |                                 ^
/Applications/Xcode2.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/17/include/__stddef_null.h:26:14: note: expanded from macro 'NULL'
   26 | #define NULL ((void*)0)
      |              ^
1 warning and 3 errors generated.
Error in child process '/usr/bin/xcrun'. 1
SUBCOMMAND: # @@upb//upbc:plugin_upb_proto_stage0 [action 'Linking external/upb/upbc/libplugin_upb_proto_stage0.a [for tool]', configuration: 882b93e5f5200c0586a435ce65150cfb9a76e41ebc396afbf7627aa541370918, execution platform: @@platforms//host:host, mnemonic: CppArchive]
(cd /private/var/tmp/_bazel_abinshahab/776cd7d396f0cd8906d56f52cbbbea44/execroot/_main && \
  exec env - \
    APPLE_SDK_PLATFORM=iPhoneOS \
    APPLE_SDK_VERSION_OVERRIDE=18.4 \
    PATH=/Users/abinshahab/Library/Caches/bazelisk/downloads/sha256/45cca81a839d7495258b19ee8371c7b891f350586ef37b9940f7b531eb654cc8/bin:/Users/abinshahab/.pyenv/versions/3.9.11/bin:/opt/homebrew/Cellar/pyenv/2.5.3/libexec:/opt/homebrew/Cellar/pyenv/2.5.3/plugins/python-build/bin:/Users/abinshahab/.atuin/bin:/opt/homebrew/opt/sqlite/bin:/Users/abinshahab/go/1.22.4/bin:/Users/abinshahab/.goenv/versions/1.22.4/bin:/Users/abinshahab/.goenv/bin:/Users/abinshahab/.nvm/versions/node/v16.18.0/bin:/Users/abinshahab/.krew/bin:/Users/abinshahab/.pyenv/shims:/Users/abinshahab/.local/bin:/usr/local/go/bin:/opt/homebrew/bin:/usr/local/bin:/System/Cryptexes/App/usr/bin:/usr/bin:/bin:/usr/sbin:/sbin:/opt/homebrew/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/local/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/appleinternal/bin:/opt/appleinternal/bin:/opt/apple/bin:/Library/Apple/usr/bin:/opt/xbs/bin:/usr/appleinternal/bin:/private/var/tanuki:/Applications/Wireshark.app/Contents/MacOS:/usr/local/go/bin:/opt/homebrew/bin:/Users/abinshahab/.goenv/shims \
    XCODE_VERSION_OVERRIDE=16.3.0.16E6140e \
    ZERO_AR_DATE=1 \
  external/local_config_apple_cc/libtool -D -no_warning_for_no_symbols -static -o bazel-out/darwin_arm64-opt-exec-ST-4b10531d2bd0/bin/external/upb/upbc/libplugin_upb_proto_stage0.a bazel-out/darwin_arm64-opt-exec-ST-4b10531d2bd0/bin/external/upb/upbc/_objs/plugin_upb_proto_stage0/plugin.upb.o)
ERROR: /Users/abinshahab/dev/ray/cpp/BUILD.bazel:29:11 Compiling cpp/src/ray/api.cc failed: (Exit 1): sandbox-exec failed: error executing CppCompile command
  (cd /private/var/tmp/_bazel_abinshahab/776cd7d396f0cd8906d56f52cbbbea44/sandbox/darwin-sandbox/257/execroot/_main && \
  exec env - \
    APPLE_SDK_PLATFORM=iPhoneOS \
    APPLE_SDK_VERSION_OVERRIDE=18.4 \
    DEVELOPER_DIR=/Applications/Xcode2.app/Contents/Developer \
    PATH=/Users/abinshahab/Library/Caches/bazelisk/downloads/sha256/45cca81a839d7495258b19ee8371c7b891f350586ef37b9940f7b531eb654cc8/bin:/Users/abinshahab/.pyenv/versions/3.9.11/bin:/opt/homebrew/Cellar/pyenv/2.5.3/libexec:/opt/homebrew/Cellar/pyenv/2.5.3/plugins/python-build/bin:/Users/abinshahab/.atuin/bin:/opt/homebrew/opt/sqlite/bin:/Users/abinshahab/go/1.22.4/bin:/Users/abinshahab/.goenv/versions/1.22.4/bin:/Users/abinshahab/.goenv/bin:/Users/abinshahab/.nvm/versions/node/v16.18.0/bin:/Users/abinshahab/.krew/bin:/Users/abinshahab/.pyenv/shims:/Users/abinshahab/.local/bin:/usr/local/go/bin:/opt/homebrew/bin:/usr/local/bin:/System/Cryptexes/App/usr/bin:/usr/bin:/bin:/usr/sbin:/sbin:/opt/homebrew/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/local/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/appleinternal/bin:/opt/appleinternal/bin:/opt/apple/bin:/Library/Apple/usr/bin:/opt/xbs/bin:/usr/appleinternal/bin:/private/var/tanuki:/Applications/Wireshark.app/Contents/MacOS:/usr/local/go/bin:/opt/homebrew/bin:/Users/abinshahab/.goenv/shims \
    SDKROOT=/Applications/Xcode2.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS18.4.sdk \
    TMPDIR=/var/folders/yj/t4s8y78932l8st32y242jcfm0000gn/T/ \
    XCODE_VERSION_OVERRIDE=16.3.0.16E6140e \
    ZERO_AR_DATE=1 \
  /usr/bin/sandbox-exec -f /private/var/tmp/_bazel_abinshahab/776cd7d396f0cd8906d56f52cbbbea44/sandbox/darwin-sandbox/257/sandbox.sb /var/tmp/_bazel_abinshahab/install/96e26d97222159f904e14600d7490eb0/process-wrapper '--timeout=0' '--kill_delay=15' '--stats=/private/var/tmp/_bazel_abinshahab/776cd7d396f0cd8906d56f52cbbbea44/sandbox/darwin-sandbox/257/stats.out' external/local_config_apple_cc/wrapped_clang '-D_FORTIFY_SOURCE=1' -fstack-protector -fcolor-diagnostics -Wall -Wthread-safety -Wself-assign -fno-omit-frame-pointer -g0 -O2 -DNDEBUG '-DNS_BLOCK_ASSERTIONS=1' '-fdebug-prefix-map=__BAZEL_EXECUTION_ROOT__=.' '-fdebug-prefix-map=__BAZEL_XCODE_DEVELOPER_DIR__=/PLACEHOLDER_DEVELOPER_DIR' -iquote external/zlib -iquote bazel-out/darwin_arm64-opt-exec-ST-4b10531d2bd0/bin/external/zlib -isystem external/zlib/zlib/include -isystem bazel-out/darwin_arm64-opt-exec-ST-4b10531d2bd0/bin/external/zlib/zlib/include -MD -MF bazel-out/darwin_arm64-opt-exec-ST-4b10531d2bd0/bin/external/zlib/_objs/zlib/zutil.d '-frandom-seed=bazel-out/darwin_arm64-opt-exec-ST-4b10531d2bd0/bin/external/zlib/_objs/zlib/zutil.o' -isysroot __BAZEL_XCODE_SDKROOT__ -F__BAZEL_XCODE_SDKROOT__/System/Library/Frameworks -F__BAZEL_XCODE_DEVELOPER_DIR__/Platforms/MacOSX.platform/Developer/Library/Frameworks -no-canonical-prefixes -pthread -g0 -Wno-deprecated-non-prototype -Wno-unused-variable -Wno-implicit-function-declaration -no-canonical-prefixes -Wno-builtin-macro-redefined '-D__DATE__="redacted"' '-D__TIMESTAMP__="redacted"' '-D__TIME__="redacted"' -target arm64e-apple-ios18.4 -c external/zlib/zutil.c -o bazel-out/darwin_arm64-opt-exec-ST-4b10531d2bd0/bin/external/zlib/_objs/zlib/zutil.o)
INFO: Elapsed time: 38.668s, Critical Path: 3.56s
INFO: 1856 processes: 1605 internal, 251 darwin-sandbox.