zlib error
ERROR: /private/var/tmp/_bazel_abinshahab/776cd7d396f0cd8906d56f52cbbbea44/external/zlib/BUILD.bazel:37:11: Compiling zutil.c failed: (Exit 1): sandbox-exec failed: error executing CppCompile command
  (cd /private/var/tmp/_bazel_abinshahab/776cd7d396f0cd8906d56f52cbbbea44/sandbox/darwin-sandbox/2625/execroot/_main && \
  exec env - \
    APPLE_SDK_PLATFORM=iPhoneOS \
    APPLE_SDK_VERSION_OVERRIDE=18.4internal \
    DEVELOPER_DIR=/Applications/Xcode2.app/Contents/Developer \
    PATH=/Users/abinshahab/Library/Caches/bazelisk/downloads/sha256/45cca81a839d7495258b19ee8371c7b891f350586ef37b9940f7b531eb654cc8/bin:/Users/abinshahab/.atuin/bin:/opt/homebrew/opt/sqlite/bin:/Users/abinshahab/go/1.22.4/bin:/Users/abinshahab/.goenv/versions/1.22.4/bin:/Users/abinshahab/.goenv/bin:/Users/abinshahab/.nvm/versions/node/v16.18.0/bin:/Users/abinshahab/.krew/bin:/Users/abinshahab/.pyenv/shims:/Users/abinshahab/.local/bin:/usr/local/go/bin:/opt/homebrew/bin:/usr/local/bin:/System/Cryptexes/App/usr/bin:/usr/bin:/bin:/usr/sbin:/sbin:/opt/homebrew/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/local/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/appleinternal/bin:/opt/appleinternal/bin:/opt/apple/bin:/Library/Apple/usr/bin:/opt/xbs/bin:/usr/appleinternal/bin:/private/var/tanuki:/Applications/Wireshark.app/Contents/MacOS:/usr/local/go/bin:/opt/homebrew/bin:/Users/abinshahab/.goenv/shims \
    SDKROOT=/Applications/Xcode2.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS18.4.Internal.sdk \
    TMPDIR=/var/folders/yj/t4s8y78932l8st32y242jcfm0000gn/T/ \
    XCODE_VERSION_OVERRIDE=16.3.0.16E6140e \
    ZERO_AR_DATE=1 \
  /usr/bin/sandbox-exec -f /private/var/tmp/_bazel_abinshahab/776cd7d396f0cd8906d56f52cbbbea44/sandbox/darwin-sandbox/2625/sandbox.sb /var/tmp/_bazel_abinshahab/install/96e26d97222159f904e14600d7490eb0/process-wrapper '--timeout=0' '--kill_delay=15' '--stats=/private/var/tmp/_bazel_abinshahab/776cd7d396f0cd8906d56f52cbbbea44/sandbox/darwin-sandbox/2625/stats.out' external/local_config_apple_cc/wrapped_clang '-D_FORTIFY_SOURCE=1' -fstack-protector -fcolor-diagnostics -Wall -Wthread-safety -Wself-assign -fno-omit-frame-pointer -g0 -O2 -DNDEBUG '-DNS_BLOCK_ASSERTIONS=1' '-fdebug-prefix-map=__BAZEL_EXECUTION_ROOT__=.' '-fdebug-prefix-map=__BAZEL_XCODE_DEVELOPER_DIR__=/PLACEHOLDER_DEVELOPER_DIR' -iquote external/zlib -iquote bazel-out/ios-opt/bin/external/zlib -isystem external/zlib/zlib/include -isystem bazel-out/ios-opt/bin/external/zlib/zlib/include -MD -MF bazel-out/ios-opt/bin/external/zlib/_objs/zlib/zutil.d '-frandom-seed=bazel-out/ios-opt/bin/external/zlib/_objs/zlib/zutil.o' -isysroot __BAZEL_XCODE_SDKROOT__ -F__BAZEL_XCODE_SDKROOT__/System/Library/Frameworks -F__BAZEL_XCODE_DEVELOPER_DIR__/Platforms/iPhoneOS.platform/Developer/Library/Frameworks -no-canonical-prefixes -pthread -fPIC -fPIC '-miphoneos-version-min=18.4' -Wno-deprecated-non-prototype -Wno-unused-variable -Wno-implicit-function-declaration -Werror -w '-Wno-error=implicit-function-declaration' '-Wno-error=unused-function' -Wno-missing-template-arg-list-after-template-kw -no-canonical-prefixes -Wno-builtin-macro-redefined '-D__DATE__="redacted"' '-D__TIMESTAMP__="redacted"' '-D__TIME__="redacted"' -target arm64e-apple-ios18.4 -c external/zlib/zutil.c -o bazel-out/ios-opt/bin/external/zlib/_objs/zlib/zutil.o)
In file included from external/zlib/zutil.c:10:
In file included from external/zlib/gzguts.h:21:
In file included from /Applications/Xcode2.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS18.4.Internal.sdk/usr/include/stdio.h:61:
/Applications/Xcode2.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS18.4.Internal.sdk/usr/include/_stdio.h:318:7: error: expected identifier or '('
  318 | FILE    *fdopen(int, const char *) __DARWIN_ALIAS_STARTING(__MAC_10_6, __IPHONE_2_0, __DARWIN_ALIAS(fdopen));
      |          ^
external/zlib/zutil.h:147:33: note: expanded from macro 'fdopen'
  147 | #        define fdopen(fd,mode) NULL /* No fdopen() */
      |                                 ^
/Applications/Xcode2.app/Contents/Developer/Toolchains/iOS18.4.xctoolchain/usr/lib/clang/17/include/__stddef_null.h:26:16: note: expanded from macro 'NULL'
   26 | #define NULL ((void*)0)
      |                ^
In file included from external/zlib/zutil.c:10:
In file included from external/zlib/gzguts.h:21:
In file included from /Applications/Xcode2.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS18.4.Internal.sdk/usr/include/stdio.h:61:
/Applications/Xcode2.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS18.4.Internal.sdk/usr/include/_stdio.h:318:7: error: expected ')'
external/zlib/zutil.h:147:33: note: expanded from macro 'fdopen'
  147 | #        define fdopen(fd,mode) NULL /* No fdopen() */
      |                                 ^
/Applications/Xcode2.app/Contents/Developer/Toolchains/iOS18.4.xctoolchain/usr/lib/clang/17/include/__stddef_null.h:26:16: note: expanded from macro 'NULL'
   26 | #define NULL ((void*)0)
      |                ^
/Applications/Xcode2.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS18.4.Internal.sdk/usr/include/_stdio.h:318:7: note: to match this '('
external/zlib/zutil.h:147:33: note: expanded from macro 'fdopen'
  147 | #        define fdopen(fd,mode) NULL /* No fdopen() */
      |                                 ^
/Applications/Xcode2.app/Contents/Developer/Toolchains/iOS18.4.xctoolchain/usr/lib/clang/17/include/__stddef_null.h:26:15: note: expanded from macro 'NULL'
   26 | #define NULL ((void*)0)
      |               ^
In file included from external/zlib/zutil.c:10:
In file included from external/zlib/gzguts.h:21:
In file included from /Applications/Xcode2.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS18.4.Internal.sdk/usr/include/stdio.h:61:
/Applications/Xcode2.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS18.4.Internal.sdk/usr/include/_stdio.h:318:7: error: expected ')'
  318 | FILE    *fdopen(int, const char *) __DARWIN_ALIAS_STARTING(__MAC_10_6, __IPHONE_2_0, __DARWIN_ALIAS(fdopen));
      |          ^
external/zlib/zutil.h:147:33: note: expanded from macro 'fdopen'
  147 | #        define fdopen(fd,mode) NULL /* No fdopen() */
      |                                 ^
/Applications/Xcode2.app/Contents/Developer/Toolchains/iOS18.4.xctoolchain/usr/lib/clang/17/include/__stddef_null.h:26:22: note: expanded from macro 'NULL'
   26 | #define NULL ((void*)0)
      |                      ^
/Applications/Xcode2.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS18.4.Internal.sdk/usr/include/_stdio.h:318:7: note: to match this '('
external/zlib/zutil.h:147:33: note: expanded from macro 'fdopen'
  147 | #        define fdopen(fd,mode) NULL /* No fdopen() */
      |                                 ^
/Applications/Xcode2.app/Contents/Developer/Toolchains/iOS18.4.xctoolchain/usr/lib/clang/17/include/__stddef_null.h:26:14: note: expanded from macro 'NULL'
   26 | #define NULL ((void*)0)
      |              ^
3 errors generated.
Error in child process '/usr/bin/xcrun'. 1
SUBCOMMAND: # @@protobuf~//:protoc_lib [action 'Compiling src/google/protobuf/compiler/zip_writer.cc [for tool]', configuration: ab29a209823f19391bb95febd57fca9abba0eb6cf379bfa790651288c603d131, execution platform: @@platforms//host:host, mnemonic: CppCompile]
(cd /private/var/tmp/_bazel_abinshahab/776cd7d396f0cd8906d56f52cbbbea44/execroot/_main && \
  exec env - \
    APPLE_SDK_PLATFORM=MacOSX \
    APPLE_SDK_VERSION_OVERRIDE=15.4 \
    PATH=/Users/abinshahab/Library/Caches/bazelisk/downloads/sha256/45cca81a839d7495258b19ee8371c7b891f350586ef37b9940f7b531eb654cc8/bin:/Users/abinshahab/.atuin/bin:/opt/homebrew/opt/sqlite/bin:/Users/abinshahab/go/1.22.4/bin:/Users/abinshahab/.goenv/versions/1.22.4/bin:/Users/abinshahab/.goenv/bin:/Users/abinshahab/.nvm/versions/node/v16.18.0/bin:/Users/abinshahab/.krew/bin:/Users/abinshahab/.pyenv/shims:/Users/abinshahab/.local/bin:/usr/local/go/bin:/opt/homebrew/bin:/usr/local/bin:/System/Cryptexes/App/usr/bin:/usr/bin:/bin:/usr/sbin:/sbin:/opt/homebrew/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/local/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/appleinternal/bin:/opt/appleinternal/bin:/opt/apple/bin:/Library/Apple/usr/bin:/opt/xbs/bin:/usr/appleinternal/bin:/private/var/tanuki:/Applications/Wireshark.app/Contents/MacOS:/usr/local/go/bin:/opt/homebrew/bin:/Users/abinshahab/.goenv/shims \
    XCODE_VERSION_OVERRIDE=16.3.0.16E6140e \
    ZERO_AR_DATE=1 \
  external/local_config_apple_cc/wrapped_clang_pp '-D_FORTIFY_SOURCE=1' -fstack-protector -fcolor-diagnostics -Wall -Wthread-safety -Wself-assign -fno-omit-frame-pointer -g0 -O2 -DNDEBUG '-DNS_BLOCK_ASSERTIONS=1' '-std=c++14' '-fdebug-prefix-map=__BAZEL_EXECUTION_ROOT__=.' '-fdebug-prefix-map=__BAZEL_XCODE_DEVELOPER_DIR__=/PLACEHOLDER_DEVELOPER_DIR' -iquote external/protobuf~ -iquote bazel-out/darwin_arm64-opt-exec/bin/external/protobuf~ -iquote external/zlib~ -iquote bazel-out/darwin_arm64-opt-exec/bin/external/zlib~ -isystem external/protobuf~/src -isystem bazel-out/darwin_arm64-opt-exec/bin/external/protobuf~/src -isystem external/zlib~/zlib/include -isystem bazel-out/darwin_arm64-opt-exec/bin/external/zlib~/zlib/include -MD -MF bazel-out/darwin_arm64-opt-exec/bin/external/protobuf~/_objs/protoc_lib/zip_writer.d '-frandom-seed=bazel-out/darwin_arm64-opt-exec/bin/external/protobuf~/_objs/protoc_lib/zip_writer.o' -isysroot __BAZEL_XCODE_SDKROOT__ -F__BAZEL_XCODE_SDKROOT__/System/Library/Frameworks -F__BAZEL_XCODE_DEVELOPER_DIR__/Platforms/MacOSX.platform/Developer/Library/Frameworks -no-canonical-prefixes -pthread -g0 -w -g0 '-std=c++17' '-std=c++17' -DHAVE_ZLIB -Woverloaded-virtual -Wno-sign-compare -no-canonical-prefixes -Wno-builtin-macro-redefined '-D__DATE__="redacted"' '-D__TIMESTAMP__="redacted"' '-D__TIME__="redacted"' -target arm64-apple-macosx15.4 -c external/protobuf~/src/google/protobuf/compiler/zip_writer.cc -o bazel-out/darwin_arm64-opt-exec/bin/external/protobuf~/_objs/protoc_lib/zip_writer.o)
Target //src/ray/gcs:gcs failed to build
INFO: Elapsed time: 15.334s, Critical Path: 6.36s
INFO: 273 processes: 14 internal, 259 darwin-sandbox.
ERROR: Build did NOT complete successfully